using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BLL;
using Model;

namespace Controls.Agent
{
    public static class AgentCtrl
    {
        public static string GetAgentList(int pageIndex)
        {
            return CommonLib.Helper.JsonSerializeObject(Sys_agent_messBLL.GetAgentList(pageIndex));

        }

        public static string ChangeStatus(int curStat,int id)
        {
            return Sys_agent_messBLL.ChangeStatus(curStat, id);
        }

        public static string ChangeGroup(int curStat, int id)
        {
            return Sys_agent_messBLL.ChangeGroup(curStat, id);
        }

        public static string AddAgent(AgentModel model)
        {
            return Sys_agent_messBLL.AddAgent(model);
        }

        public static AgentModel GetSingleModel(int id)
        {
            return Sys_agent_messBLL.GetSingleModel(id);
        }

        public static string GetAgentStat(string stDate, string edDate,string[] cols)
        {
            return CommonLib.Helper.JsonSerializeObject(Sys_agent_messBLL.GetAngentStat(stDate, edDate, cols));
        }

        public static string GetRandomNum()
        {
            return Sys_agent_messBLL.GetRandomNum();
        }

        public static string ModifyAgentInfo(AgentModel model)
        {
            return Sys_agent_messBLL.ModifyAgentInfo(model);
        }

        /// <summary>
        /// 产生并校验代理商编码
        /// </summary>
        /// <param name="agentName"></param>
        /// <returns></returns>
        public static string CheckAndAutoGeneratedCode(string agentName)
        {
            return Sys_agent_messBLL.CheckAndAutoGeneratedCode(agentName);
        }
    }
}
