using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Controls.Agent;
using Model;
using OperationPlatform.HelperEx;

namespace OperationPlatform.Controllers
{
    [OperationPlatform.App_Start.LoginAuthentication]
    public class AgentController : Controller
    {
        // GET: Agent
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddNewAgent()
        {
            //ViewBag.AgentBh = GetRandomNum();
            return View();
        }

        public ActionResult AgentDetail(int id)
        {
            AgentModel model = AgentCtrl.GetSingleModel(id);
            return View(model);
        }

        public ActionResult AgentModify(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        public string GetSingleModel(int id)
        {
            return CommonLib.Helper.JsonSerializeObject(AgentCtrl.GetSingleModel(id));
        }

        public string ModifyAgentInfo(AgentModel model)
        {
            return AgentCtrl.ModifyAgentInfo(model);
        }

        public ActionResult AgentStat()
        {
            return View();
        }

        public string GetAgentList(int pageIndex)
        {
            return AgentCtrl.GetAgentList(pageIndex);
        }

        public string GetRandomNum()
        {
            return AgentCtrl.GetRandomNum();
        }

        public string ChangeStatus(int curStat,int id)
        {
            return AgentCtrl.ChangeStatus(curStat, id);
        }

        public string ChangeGroup(int curStat, int id)
        {
            return AgentCtrl.ChangeGroup(curStat, id);
        }

        public string GetAgentStat(string stTime, string edTime, string columns)
        {
            string[] cs = columns.Split(',');
            return AgentCtrl.GetAgentStat(stTime, edTime, cs);
        }

        public string AddAgent(string agentId, string agentPwd, string agentPhone, string agentName, string agentAddress, int agentGrade, string agentIdCard,
            string agentNumber, string agentEmail, string agentQq, string remark,int serviceType)
        {
            AgentModel model = new AgentModel();
            model.AgentId = agentId;
            model.AgentPassword = CommonLib.Helper.Md5Hash(agentPwd);
            model.AgentPhone = agentPhone;
            model.AgentName = agentName;
            model.AgentAddress = agentAddress;
            model.AgentGrade = agentGrade;
            model.AgentIdCard = agentIdCard;
            model.AgentNumber = agentNumber;
            model.AgentEmail = agentEmail;
            model.AgentQQ = agentQq;
            model.Remark = remark;
            model.ServiceType = serviceType;

            ManageUserModel uM = (ManageUserModel)Session["logUser"];
            if (uM!=null)
            {
                model.Creater = uM.Name;
            }

            model.AgentLink = "http://app.i200.cn/LoginReg/Registration.aspx?ag=";
           //舍弃加密方式的代理商编码
           //model.AgentLink += (new Class_Password()).EnCode(agentId);
            model.AgentLink += agentId;

            return AgentCtrl.AddAgent(model);
        }


        /// <summary>
        /// 产生并校验代理商编码
        /// </summary>
        /// <param name="agentName"></param>
        /// <returns></returns>
        public string CheckAndAutoGeneratedCode(string agentName)
        {
            return AgentCtrl.CheckAndAutoGeneratedCode(agentName);
        }
    }
}
