using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DAL;
using Model;

namespace BLL
{
    public static class Sys_agent_messBLL
    {
        public static AgentList GetAgentList(int pageIndex)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.GetAgentList(pageIndex);
        }

        public static string ChangeStatus(int curStat,int id)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.ChangeStatus(curStat, id);
        }

        public static string ChangeGroup(int curStat, int id)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.ChangeGroup(curStat, id);
        }

        public static string AddAgent(AgentModel model)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.AddAgent(model);
        }

        public static AgentModel GetSingleModel(int id)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.GetSingleModel(id);
        }

        public static chartDataModel GetAngentStat(string stDate, string edDate, string[] cols)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.GetAgentStat(stDate, edDate, cols);

        }

        public static string GetRandomNum()
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.GetRandomNum();
        }

        public static string ModifyAgentInfo(AgentModel model)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.ModifyAgentInfo(model);
        }

        /// <summary>
        /// 产生并校验代理商编码
        /// </summary>
        /// <param name="agentName"></param>
        /// <returns></returns>
        public static string CheckAndAutoGeneratedCode(string agentName)
        {
            Sys_agent_messDAL dal = new Sys_agent_messDAL();
            return dal.CheckAndAutoGeneratedCode(agentName);
        }
    }
}
